import 'dart:math' as math;

/// One-shot sound effects (`assets/audio/sfx/`, generated by
/// `tool/audio/generate_audio.py`).
///
/// [cooldownMs] drops repeats that come faster than that (sounds a player can
/// trigger by tapping repeatedly get about their own length); [vary] is the
/// random ± play-rate per play, so repeats don't sound identical.
enum Sfx {
  click('click', cooldownMs: 40, vary: .04),
  deny('deny'),
  bootTick('boot_tick', vary: .03),
  bootOk('boot_ok'),
  hello('hello'),
  type('type', cooldownMs: 45, vary: .08),
  good('good'),
  lie('lie'),
  voice('voice', cooldownMs: 1000),
  step('step'),
  stepWatch('step_watch'),
  doorLocked('door_locked', cooldownMs: 500),
  doorOpen('door_open'),
  drawerOpen('drawer_open'),
  key('key'),
  crack('crack'),
  dial('dial', cooldownMs: 30),
  wrong('wrong', cooldownMs: 300),
  wrongLied('wrong_lied', cooldownMs: 480),
  unlock('unlock'),
  glitchLight('glitch_light', cooldownMs: 900, vary: .12),
  glitchHeavy('glitch_heavy', cooldownMs: 900, vary: .12),
  tear('tear'),
  tearOpen('tear_open'),
  light('light'),
  fade('fade'),
  pause('pause', cooldownMs: 150),
  resume('resume', cooldownMs: 150);

  const Sfx(this.file, {this.cooldownMs = 0, this.vary = 0});
  final String file;
  final int cooldownMs;
  final double vary;

  String get asset => 'assets/audio/sfx/$file.wav';
}

/// What the music is doing. One loop plays at a time; the game picks the
/// mood from its state (see `GameController.mood`).
enum Mood {
  silence(null),

  /// The lullaby: menu, 01, 02 before the lie, ending TRUST.
  trust('trust', fadeInMs: 2500),

  /// The same song caught lying (02 after "I LIED.").
  lie('lie', fadeInMs: 1800),

  /// 03 UI GLITCH.
  broken('broken', fadeInMs: 400),

  /// 04: slower, notes missing, a pulse.
  watching('watching', fadeInMs: 1500),

  /// 05: no music, only the room.
  room('room', fadeInMs: 2500),

  /// Ending DON'T TRUST: open air.
  exit('exit', fadeInMs: 2500),

  /// Ending TRUE: one pure chord, played once.
  truthEnd('true', loop: false);

  const Mood(this._file, {this.fadeInMs = 0, this.loop = true});
  final String? _file;
  final int fadeInMs;
  final bool loop;

  String? get asset => _file == null ? null : 'assets/audio/music/$_file.ogg';
}

/// Settings level (0–10) → linear gain: 10 is 0 dB, each step −3 dB, 0 mutes.
double volumeGain(int level) =>
    level <= 0 ? 0 : math.pow(10, (level - 10) * 3 / 20).toDouble();
